### PR TITLE
Add mjs for browser modules

### PR DESCRIPTION
**Pull request by sagea**
**PR Description**
Adds a bundle for browser modules.

**Reason For Creating:**
I would just like to import this module using browser modules via unpkg.com for my personal projects.

**Context Notes:**
1. The `es` bundle destination folder was decided so it matched how the redux repository does it.

### CODE REVIEW

**Comment by tshelburne** [comment]
@sagea Hey, thanks for submitting this - I completely lost track of it, but just started checking through live PRs this weekend of my libs. If you can fix the conflicts (let's keep .babelrc and go with the recent version updates) then I'm happy to merge for es modules support.

**Comment by sagea** [comment]
@tshelburne No worries, I will get to this in a few minutes

**Comment by sagea** [comment]
@tshelburne done.
1. Switched back to .babelrc
2. Used the updated dependency versions from master
3. Updated to the latest babel dependencies
4. Added a umd bundle as well. Redux does this and unpkg.com will host it.

**Comment by tshelburne** [comment]
@sagea Published 0.5.0 to npm!

**Comment by sagea** [comment]
@tshelburne Awesome, Thanks! stay safe my friend

**Pull request merged**
