### PR TITLE
Add typescript type declarations

### PR DESCRIPTION
**Pull request by mDibyo**
Adding typescript declarations to make this easier to use with typescript projects. :)

@tshelburne, would be down to add a typescript version if you are interested!

### CODE REVIEW

**Comment by tshelburne** [comment]
@dibyo Thanks, this is great! I hadn't even thought about adding a defs file.

Re: a typescript version, I don't think the module itself is complex enough to benefit from it, especially since it would require the extra dev dep. However, if people start asking for it for reassurance or something, I'm not opposed.

Thanks again!

**Comment by tshelburne** [comment]
@dibyo Also, new version published to NPM, 0.1.5.

**Comment by mDibyo** [comment]
@tshelburne think you have the wrong @dibyo there. :D

yeah, you are right about it not being complex enough to benefit much from typescripting. 

Thanks for the new version! I can stop relying on my local version of the package now!

**Comment by tshelburne** [comment]
@mDibyo Oh damn. I was wondering why the autocomplete was feeling slow.

Thanks for the pull.

**Pull request merged**
